POST http://localhost:7000/users
content-type: application/json

{
   "first_name": "Nonso",
    "last_name": "Obodo",
    "email": "nonsoobodo@gmail.com",
    "phone": "08023456588",
    "next_of_kind": "Chucks Obodo",
    "dob": "04/08/1999",
    "password": "password123"
}