POST http://localhost:3000/users/1/withdraw
content-type: application/json

{
    "amount": 9000
}

Good day sir/ma'am!
Please I urgently need your help/assistance to deploy my app here successfully, I have been trying to deploy my node js typescript express server app but unfortunately, all my efforts seemed abortive 
I tested the project locally and everything is working correctly but if I try deploying the app here it fails.
The project's GitHub repo: https://github.com/chiedozie07/demo-credit

Here are the log details:



